AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5.0
  Exclude:
    - vendor/**/*

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - ./*.gemspec
    - spec/**/*.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SymbolProc:
  Enabled: false
