require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5.0
  Exclude:
    - vendor/**/*

Layout/LineLength:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - ./*.gemspec
    - spec/**/*.rb
    - tasks/**/*.rake

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SymbolProc:
  Enabled: false
