AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SymbolProc:
  Enabled: false
