language: ruby
os:
  - osx
  - linux
rvm:
  - 2.6
  - 2.5
  - 2.4
before_install:
  - gem update --system
  - gem install bundler
cache: bundler
script: bundle exec rake test
branches:
  only: master
