[package]
name = "rusty_lru"
version = "0.1.2"
authors = ["Alastair Pharo <me@asph.dev>"]
edition = "2018"

[dependencies]
rutie = "0.8.2"
lru = "0.6.5"
lazy_static = "1.4.0"

[lib]
name = "rusty_lru"
crate-type = ["dylib"]
