[package]
name = "rusty_lru"
version = "0.1.1"
authors = ["Alastair Pharo <me@asph.dev>"]
edition = "2018"

[dependencies]
rutie = "0.6.1"
lru = "0.1.17"
lazy_static = "1.3.0"

[lib]
name = "rusty_lru"
crate-type = ["dylib"]
