name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cargo-test:
    name: Cargo test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        rust-version: [stable, nightly]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust ${{ matrix.rust-version }}
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust-version }}
        override: true

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler: latest
        bundler-cache: true

    - name: Cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

  rspec:
    name: RSpec
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        ruby-version: [3.0, 2.7, 2.6, 2.5]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: latest
        bundler-cache: true

    - name: RSpec
      run: bundle exec rake spec

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler: latest
        bundler-cache: true

    - name: Rubocop
      run: bundle exec rubocop
